//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppKondi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public long MasterID { get; set; }
        public long RequestID { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual User Master { get; set; }
    }
}
