//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppKondi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public long Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public long ClimateTechTypeId { get; set; }
        public string ClimateTechModel { get; set; }
        public string ProblemDescryption { get; set; }
        public long RequestStatusId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string RepairParts { get; set; }
        public Nullable<long> MasterId { get; set; }
        public long ClientId { get; set; }
    
        public virtual ClimateTechType ClimateTechType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual User Master { get; set; }
        public virtual User Client { get; set; }
    }
}
